inherit_gem:
  hint-rubocop_style:
    - default.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile*'
    - 'script/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
