version: '3'
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - gems:/gems
    ports:
      - "3000:3000"
      - "1080:1080"
      - "43447:43447"
    depends_on:
      - postgres
    entrypoint: /app/dev-entrypoint
    tty: true
    stdin_open: true
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
      - SELENIUM_REMOTE_HOST=selenium
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 5900:5900
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - gems:/gems
    ports:
      - "3035:3035"
    entrypoint: /app/docker/webpack-entrypoint
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  gems:
