version: '3.1'
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - gems:/gems
    ports:
      - "3000:3000"
      - "1080:1080"
    depends_on:
      - postgres
    entrypoint: /app/dev-entrypoint
    tty: true
    stdin_open: true
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  gems:
