version: '3'
services:
  app:
    build:
      context: ./docker/ruby
      args:
        - INSTALL_PG_CLIENT=true
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - gems:/gems
    ports:
      - "3000:3000"
      - "1080:1080"
    depends_on:
      - postgres
      - redis
    entrypoint: /app/dev-entrypoint
    tty: true
    stdin_open: true
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
  webpacker:
    build:
      context: ./docker/ruby
      args:
        - INSTALL_PG_CLIENT=false
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - gems:/gems
    ports:
      - "3035:3035"
    entrypoint: /app/docker/webpack-entrypoint
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    build:
      context: ./docker/redis
      args:
        - REDIS_VERSION=3.2
    ports:
      - "6379"
    volumes:
      - redis:/data
  sidekiq:
    build:
      context: ./docker/ruby
      args:
        - INSTALL_PG_CLIENT=true
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - gems:/gems
    entrypoint: /app/dev-entrypoint

volumes:
  postgres-data:
  gems:
  redis:
