development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: scheduler_staging

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>
  channel_prefix: scheduler_production